name: install test

on: [workflow_dispatch]
#on:
#  push:
#    branches:
#      - main

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: depend cache
        id: cache
        uses: actions/cache@v2
        env:
          CACHE_ID: 1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-depend-${{ env.CACHE_ID }}-${{ hashFiles('requirement.txt') }}
          restore-keys: |
            ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-

      - name: download and install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "maybe there are some cache i found!"
      - name: first to domain int
        run: |
          echo "here is function to detected domain from brupdns.py."
          bash ./entrypoint.sh coscoshipping.com domains
      - name: sencond to scan domains ports
        run: |
          echo "ready to scan."
          bash ./entrypoint.sh coscoshipping.com ports
      - name: thirdly to run aq-bin screenshots
        run: |
          echo "test chrome bin files."
          bash ./entrypoint.sh coscoshipping.com screens
          echo "扫描完成，这里是附件" > result.html
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.com
          server_port: 465
          #username: ${{ secrets.MAIL_USERNAME }}
          #password: ${{ secrets.MAIL_PASSWORD }}
          username: ${{secrets.SENTRY_MAIL_USERNAME}}
          password: ${{secrets.SENTRY_MAIL_PASSWORD}}
          subject: "您的订阅信息"
          html_body: file://result.html
          to: bin4xin.sentrylab@qq.com
          #cc: chihou.pro@gmail.com
          #from: 哨兵 -  ${{ env.REPORT_COMMIT }}
          from: 哨兵 - 望远镜
          content_type: text/html
          attachments: attachments.tar.gz