name: TELESCOPE WORKFLOW

on:
  workflow_dispatch:
    inputs:
      searchDomain:
        description: "Please enter the domain name to be scanned"
        required: true
        default: "csleasing.com.cn"
      #Nmap_Parameter:
        #description: "Custom parameter information scanned by nmap. The format when scanning is: nmap <custom parameter> -iL xxx.txt -oX xxx.xml"
        #required: true
        #default: "-p- -v -sV"

env:
  searchDomain: "${{ github.event.inputs.searchDomain }}"  #set up scan target


jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      LSI: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: depend cache
        id: cache
        uses: actions/cache@v2
        env:
          CACHE_ID: 1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-depend-${{ env.CACHE_ID }}-${{ hashFiles('requirement.txt') }}
          restore-keys: |
            ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-

      - name: download and install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "maybe there are some cache i found!"

  Domain_Search:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: first to domain int
        run: |
          echo "here is function to detected domain from brupdns.py."
          bash ./entrypoint.sh domains

  Domain_InfoScan:
    needs: Domain_Search
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: sencond to scan domains ports
        run: |
          echo "ready to scan."
          bash ./entrypoint.sh ports

  Domain_ScreenshotsInfo:
    needs: Domain_InfoScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: thirdly to run aq-bin screenshots
        run: |
          bash ./entrypoint.sh screens
          echo "扫描完成，这里是附件" > result.html

  SendMails:
    needs: Domain_ScreenshotsInfo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.com
          server_port: 465
          #username: ${{ secrets.MAIL_USERNAME }}
          #password: ${{ secrets.MAIL_PASSWORD }}
          username: ${{secrets.SENTRY_MAIL_USERNAME}}
          password: ${{secrets.SENTRY_MAIL_PASSWORD}}
          subject: "您的订阅信息"
          html_body: file://result.html
          to: bin4xin.sentrylab@qq.com
          #cc: chihou.pro@gmail.com
          #from: 哨兵 -  ${{ env.REPORT_COMMIT }}
          from: 哨兵 - 望远镜
          content_type: text/html
          attachments: attachments.tar.gz